<Project Sdk="Microsoft.NET.Sdk">
	<PropertyGroup>
		<TargetFramework>net10.0-windows10.0.19041.0</TargetFramework>
		<RootNamespace>Rufus.Tests.MSTest</RootNamespace>
		<Platforms>x64</Platforms>
		<IsPackable>false</IsPackable>
		<ImplicitUsings>enable</ImplicitUsings>
		<Nullable>enable</Nullable>
		<UseWinUI>true</UseWinUI>
		<ProjectPriFileName>resources.pri</ProjectPriFileName>
	</PropertyGroup>
	<ItemGroup>
		<PackageReference Include="coverlet.collector" Version="10.0.1" />
		<PackageReference Include="Microsoft.NET.Test.Sdk" Version="18.10.1" />
		<PackageReference Include="MSTest.TestAdapter" Version="4.4.1" />
		<PackageReference Include="MSTest.TestFramework" Version="4.4.1" />
	</ItemGroup>
	<ItemGroup>
		<ProjectReference Include="..\Rufus\Rufus.csproj" />
	</ItemGroup>
</Project>
